In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score

In [2]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

In [3]:
df= pd.read_csv('/kaggle/input/iris-leaf-classification-dataset/IRIS.csv')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)
df_shuffled.head()

   sepal_length  sepal_width  petal_length  petal_width          species
0           6.1          2.8           4.7          1.2  Iris-versicolor
1           5.7          3.8           1.7          0.3      Iris-setosa
2           7.7          2.6           6.9          2.3   Iris-virginica
3           6.0          2.9           4.5          1.5  Iris-versicolor
4           6.8          2.8           4.8          1.4  Iris-versicolor

In [6]:
df_shuffled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [9]:
X = df_shuffled.iloc[:,0:4]
y = df_shuffled["species"]

In [10]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             6.1          2.8           4.7          1.2
1             5.7          3.8           1.7          0.3
2             7.7          2.6           6.9          2.3
3             6.0          2.9           4.5          1.5
4             6.8          2.8           4.8          1.4
..            ...          ...           ...          ...
145           6.1          2.8           4.0          1.3
146           4.9          2.5           4.5          1.7
147           5.8          4.0           1.2          0.2
148           5.8          2.6           4.0          1.2
149           7.1          3.0           5.9          2.1

[150 rows x 4 columns]

In [11]:
y

0      Iris-versicolor
1          Iris-setosa
2       Iris-virginica
3      Iris-versicolor
4      Iris-versicolor
            ...
145    Iris-versicolor
146     Iris-virginica
147        Iris-setosa
148    Iris-versicolor
149     Iris-virginica
Name: species, Length: 150, dtype: object

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model = LogisticRegression(multi_class="multinomial", solver="lbfgs", max_iter=200)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [16]:
y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

In [18]:
from sklearn.metrics import classification_report

In [19]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9777777777777777

Confusion Matrix:
 [[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.94      1.00      0.97        15
 Iris-virginica       1.00      0.93      0.97        15

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45